# -*- coding: utf-8 -*-
"""Project-4app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z1vesg-sjWg1rFKHn58j783Tj4pVnpuS
"""

import streamlit as st
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

# ---------------------------------
# Page Configuration
# ---------------------------------
st.set_page_config(
    page_title="Employee Retention Prediction",
    page_icon="👨‍💼",
    layout="wide"
)

# ---------------------------------
# Title
# ---------------------------------
st.title("👨‍💼 Employee Retention Prediction")
st.write("""
This application analyzes employee data and predicts whether an employee is likely
to leave the company using **Logistic Regression**.
""")

# ---------------------------------
# Load Dataset
# ---------------------------------
@st.cache_data
def load_data():
    return pd.read_csv("HR_comma_sep.csv")

df = load_data()

# ---------------------------------
# Dataset Preview
# ---------------------------------
st.header("Dataset Preview")
st.dataframe(df.head())

st.write("Dataset Shape:", df.shape)

# ---------------------------------
# Employees Left & Retained
# ---------------------------------
left = df[df.left == 1]
retained = df[df.left == 0]

col1, col2 = st.columns(2)

with col1:
    st.metric("Employees Left", left.shape[0])

with col2:
    st.metric("Employees Retained", retained.shape[0])

# ---------------------------------
# Average Values
# ---------------------------------
st.header("Average Values")

average_values = df.groupby("left").mean(numeric_only=True)
st.dataframe(average_values)

st.success("""
### Observations

• Employees with low satisfaction levels are more likely to leave.

• Employees working higher monthly hours are more likely to leave.

• Employees who received promotions are more likely to stay.

• Employees with higher salaries are more likely to stay.
""")

# ---------------------------------
# Salary Impact
# ---------------------------------
st.header("Impact of Salary on Employee Retention")

salary_chart = pd.crosstab(df["salary"], df["left"])
st.bar_chart(salary_chart)

# ---------------------------------
# Department Impact
# ---------------------------------
st.header("Department-wise Employee Retention")

department_chart = pd.crosstab(df["Department"], df["left"])
st.bar_chart(department_chart)

st.info("Department has only a minor impact on retention, so it is not used in model training.")

# ---------------------------------
# Feature Selection
# ---------------------------------
subdf = df[[
    "satisfaction_level",
    "average_montly_hours",
    "promotion_last_5years",
    "salary"
]]

# One Hot Encoding
salary_dummies = pd.get_dummies(subdf["salary"], prefix="salary")

df_with_dummies = pd.concat([subdf, salary_dummies], axis=1)

df_with_dummies.drop("salary", axis=1, inplace=True)

X = df_with_dummies
y = df["left"]

# ---------------------------------
# Train Test Split
# ---------------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    train_size=0.30,
    random_state=42
)

# ---------------------------------
# Model Training
# ---------------------------------
model = LogisticRegression(max_iter=1000)

model.fit(X_train, y_train)

accuracy = model.score(X_test, y_test)

st.header("Model Accuracy")
st.success(f"Accuracy: {accuracy*100:.2f}%")

# ---------------------------------
# Prediction
# ---------------------------------
st.header("Predict Employee Retention")

satisfaction = st.slider(
    "Satisfaction Level",
    0.0,
    1.0,
    0.50
)

hours = st.slider(
    "Average Monthly Hours",
    80,
    320,
    200
)

promotion = st.selectbox(
    "Promotion in Last 5 Years",
    [0, 1]
)

salary = st.selectbox(
    "Salary Level",
    ["low", "medium", "high"]
)

salary_low = 0
salary_medium = 0
salary_high = 0

if salary == "low":
    salary_low = 1
elif salary == "medium":
    salary_medium = 1
else:
    salary_high = 1

if st.button("Predict"):

    input_data = pd.DataFrame({
        "satisfaction_level": [satisfaction],
        "average_montly_hours": [hours],
        "promotion_last_5years": [promotion],
        "salary_high": [salary_high],
        "salary_low": [salary_low],
        "salary_medium": [salary_medium]
    })

    prediction = model.predict(input_data)

    probability = model.predict_proba(input_data)

    if prediction[0] == 1:
        st.error("⚠️ The employee is likely to leave the company.")
    else:
        st.success("✅ The employee is likely to stay in the company.")

    st.write(f"Probability of Staying: **{probability[0][0]*100:.2f}%**")
    st.write(f"Probability of Leaving: **{probability[0][1]*100:.2f}%**")